"""Exploratory data analysis of the training and validation data.

    .venv/bin/python notebooks/03_eda.py

Writes reports/eda_summary.md and charts to reports/figures/eda_*.png.
"""

import json
from collections import Counter

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer

from report_style import BLUE, ORANGE, REPORTS, ROOT, TEXT_2, hbar, plt, save

LANG_ORDER = ["en", "singlish", "si", "ta", "tanglish", "mixed"]


def load(name):
    with open(ROOT / "data" / name, encoding="utf-8") as f:
        return pd.DataFrame([json.loads(line) for line in f])


def nearest_neighbours(train, val):
    """How similar is each ticket to its closest training ticket, and does that neighbour share its category?

    Explains why random k-fold CV on train is far too optimistic: train contains near-paraphrases.
    """
    vec = TfidfVectorizer(analyzer="char_wb", ngram_range=(3, 5), min_df=2, sublinear_tf=True).fit(train["text"])
    A, B = vec.transform(train["text"]), vec.transform(val["text"])
    out = {}
    for name, sims, labels in [("train -> other train", (A @ A.T).toarray(), train["category"].values),
                               ("validation -> train", (B @ A.T).toarray(), val["category"].values)]:
        if sims.shape[0] == sims.shape[1]:
            np.fill_diagonal(sims, 0)
        nn = sims.argmax(1)
        out[name] = {"median_sim": float(np.median(sims.max(1))), "over_0_8": float(np.mean(sims.max(1) > 0.8)),
                     "same_category": float(np.mean(train["category"].values[nn] == labels))}
    return out


def main():
    train, val = load("train.jsonl"), load("validation.jsonl")
    both = pd.concat([train.assign(split="train"), val.assign(split="validation")], ignore_index=True)
    both["chars"] = both["text"].str.len()
    both["has_subject"] = both["subject"].fillna("").str.strip() != ""
    both["has_secondary"] = both["secondary_category"].notna()
    tr = both[both.split == "train"]

    # ---- facts for the report ----
    dup_in_train = int(tr["text"].duplicated().sum())
    overlap = len(set(train["text"]) & set(val["text"]))
    missing = {c: int(both[c].isna().sum()) for c in ["channel", "text", "category", "is_urgent"]}
    cat_counts = tr["category"].value_counts()
    lines = [
        "# EDA summary (generated by notebooks/03_eda.py)", "",
        f"- Tickets: train {len(train):,}, validation {len(val):,}",
        f"- Missing values in required columns: {missing}",
        f"- Exact duplicate texts inside train: {dup_in_train}; texts shared by train and validation: {overlap}",
        f"- Category imbalance (train): largest `{cat_counts.index[0]}` {cat_counts.iloc[0]}, "
        f"smallest `{cat_counts.index[-1]}` {cat_counts.iloc[-1]} (ratio {cat_counts.iloc[0] / cat_counts.iloc[-1]:.1f}x)",
        f"- Urgent: {tr['is_urgent'].mean():.1%} of train tickets",
        f"- Has a secondary category: {tr['has_secondary'].mean():.1%}",
        f"- Email tickets with a subject: {tr[tr.channel == 'email']['has_subject'].mean():.1%}",
        f"- Text length (characters): median {int(tr['chars'].median())}, 95th percentile {int(tr['chars'].quantile(.95))}, "
        f"max {int(tr['chars'].max())}",
    ]
    lines += ["", "## Nearest-neighbour check (character TF-IDF cosine similarity)", "",
              "| query | median similarity to nearest train ticket | share above 0.8 | nearest has same category |",
              "|---|---|---|---|"]
    for name, r in nearest_neighbours(train, val).items():
        lines.append(f"| {name} | {r['median_sim']:.3f} | {r['over_0_8']:.1%} | {r['same_category']:.1%} |")
    lines += [
        "", "Train tickets have close paraphrases inside train, validation tickets mostly do not. Random k-fold CV on",
        "train therefore scores ~98% while the same models score 53-65% on validation; we select models on validation.",
        "", "## Train counts", "",
        "| category | tickets | urgent % | with secondary % |", "|---|---|---|---|",
    ]
    for cat in cat_counts.index:
        sub = tr[tr.category == cat]
        lines.append(f"| {cat} | {len(sub)} | {sub['is_urgent'].mean():.0%} | {sub['has_secondary'].mean():.0%} |")
    lines += ["", "| language | tickets | share | median chars |", "|---|---|---|---|"]
    for lang in LANG_ORDER:
        sub = tr[tr.language == lang]
        lines.append(f"| {lang} | {len(sub)} | {len(sub) / len(tr):.1%} | {int(sub['chars'].median())} |")
    lines += ["", "| channel | tickets |", "|---|---|"]
    lines += [f"| {k} | {v} |" for k, v in tr["channel"].value_counts().items()]
    REPORTS.mkdir(exist_ok=True)
    (REPORTS / "eda_summary.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print("  wrote reports/eda_summary.md")

    # ---- charts ----
    fig, ax = plt.subplots(figsize=(7, 4.2))
    hbar(ax, list(cat_counts.index), list(cat_counts.values))
    ax.set_title("Training tickets per category")
    ax.set_xlabel("tickets")
    save(fig, "eda_category_counts.png")

    fig, ax = plt.subplots(figsize=(7, 3.2))
    lang_counts = tr["language"].value_counts().reindex(LANG_ORDER)
    hbar(ax, LANG_ORDER, list(lang_counts.values))
    ax.set_title("Training tickets per language (not sent to the API)")
    ax.set_xlabel("tickets")
    save(fig, "eda_language_counts.png")

    fig, ax = plt.subplots(figsize=(7, 3.6))
    data = [tr[tr.language == lang]["chars"].values for lang in LANG_ORDER]
    ax.boxplot(data, orientation="horizontal", tick_labels=LANG_ORDER, showfliers=False, widths=0.55, patch_artist=True,
               boxprops=dict(facecolor="#cfe0f5", edgecolor=BLUE), medianprops=dict(color=BLUE, linewidth=2),
               whiskerprops=dict(color=TEXT_2), capprops=dict(color=TEXT_2))
    ax.invert_yaxis()
    ax.grid(axis="y", visible=False)
    ax.set_title("Ticket length by language")
    ax.set_xlabel("characters (outliers hidden)")
    save(fig, "eda_length_by_language.png")

    fig, ax = plt.subplots(figsize=(7, 4.2))
    urgent = tr.groupby("category")["is_urgent"].mean().sort_values(ascending=False) * 100
    hbar(ax, list(urgent.index), list(urgent.values), fmt="{:.0f}%")
    ax.set_title("Share of urgent tickets per category")
    ax.set_xlabel("% urgent")
    save(fig, "eda_urgent_by_category.png")

    fig, ax = plt.subplots(figsize=(7, 4.2))
    pairs = Counter(zip(tr["category"], tr["secondary_category"].fillna("none")))
    top = [(f"{a} + {b}", n) for (a, b), n in pairs.most_common() if b != "none"][:10]
    hbar(ax, [t[0] for t in top], [t[1] for t in top], color=ORANGE)
    ax.set_title("Most common primary + secondary pairs")
    ax.set_xlabel("tickets")
    save(fig, "eda_secondary_pairs.png")


if __name__ == "__main__":
    np.random.seed(42)
    main()
